# A unique name, must eq var console/vite.config.js#pluginEntryName,
# and can not contain specific symbol such as - .
name: PluginPan115
# plugin entry class that extends BasePlugin
clazz: run.ikaros.plugin.pan115.Pan115Plugin
# plugin 'version' is a valid semantic version string (see semver.org).
version: 1.0.7
requires: ">=1.0.5"
author:
  name: Ikaros OSS Team
  website: https://github.com/ikaros-dev
logo: https://ikaros.run/logo.png
homepage: https://github.com/ikaros-dev/plugin-pan115
displayName: "115网盘插件"
description: "115网盘插件，提供对115网盘的驱动附件挂载。"
license: "AGPL-3.0"